/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#F5F1E8",
        "surface-dim": "#dbdad6",
        "surface-bright": "#F5F1E8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ECE7DD",
        "surface-container": "#E5DFD4",
        "surface-container-high": "#DDD7CB",
        "surface-container-highest": "#D5CFC2",
        "on-surface": "#191a18",
        "on-surface-variant": "#63665f",
        "inverse-surface": "#2a2b28",
        "inverse-on-surface": "#f2f1ed",
        "outline": "#787a74",
        "outline-variant": "#E0DAD0",
        "surface-tint": "#5e5e62",
        "primary": "#111210",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1f",
        "on-primary-container": "#848387",
        "secondary": "#c2410c",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffedd5",
        "on-secondary-container": "#7c2d12",
        "tertiary": "#15803d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#166534",
        "on-tertiary-container": "#dcfce7",
        "error": "#b91c1c",
        "on-error": "#ffffff",
        "error-container": "#fef2f2",
        "on-error-container": "#991b1b",
        "background": "#F5F1E8",
        "on-background": "#191a18",
        "surface-variant": "#E5DFD4",
      },
      borderRadius: {
        "none": "0px",
        "sm": "6px",
        "DEFAULT": "8px",
        "md": "8px",
        "lg": "10px",
        "xl": "12px",
        "2xl": "16px",
        "3xl": "20px",
        "full": "9999px",
      },
      fontFamily: {
        sans: ["'Inter'", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        mono: ["'JetBrains Mono'", "ui-monospace", "SFMono-Regular", "monospace"],
        serif: ["'Playfair Display'", "Georgia", "serif"],
        display: ["'Playfair Display'", "serif"],
      },
      boxShadow: {
        "xs": "0 1px 2px 0 rgba(0, 0, 0, 0.03)",
        "subtle": "0 1px 3px 0 rgba(0, 0, 0, 0.04), 0 1px 2px -1px rgba(0, 0, 0, 0.03)",
        "card": "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 4px 12px 0 rgba(0, 0, 0, 0.03)",
        "floating": "0 8px 24px -4px rgba(0, 0, 0, 0.08), 0 2px 6px -1px rgba(0, 0, 0, 0.04)",
      },
    },
  },
  plugins: [],
}
